# Generated by Django 3.2 on 2021-05-01 19:26

from django.db import migrations, models
import internationalflavor.iban.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('booking_date', models.DateField()),
                ('contractor_data', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=140)),
                ('contractor_account_number', internationalflavor.iban.models.IBANField()),
                ('contractor_bank_name', models.CharField(max_length=70)),
                ('kind', models.CharField(choices=[('TRANSFER', 'PRZELEW'), ('ORDER', 'ST.ZLEC'), ('BLIK', 'TR.BLIK'), ('CARD', 'TR.KART')], max_length=15)),
                ('number', models.CharField(max_length=50)),
                ('account_number', internationalflavor.iban.models.IBANField()),
            ],
        ),
    ]
